version: "3.9"
services:
  fastapi-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    depends_on:
      - mongo
    networks:
      - mynetwork

  mongo:
    image: mongo
    ports:
      - "27018:27017"
    networks:
      - mynetwork

networks:
  mynetwork:
